# Generated by Django 5.1.6 on 2025-04-14 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='chatrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_type', models.CharField(choices=[('message', 'message'), ('game_request', 'Game Request')], default='message', max_length=20)),
                ('request_status', models.CharField(choices=[('for_sender', 'For_Sender'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('autorejected', 'Autoejected')], default='none', max_length=15)),
                ('game_type', models.CharField(choices=[('1v1', '1v1'), ('tournament', 'Tournament')], default='none', max_length=10)),
                ('game_id', models.CharField(blank=True, default='none', max_length=8, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('autorejected', 'Autoejected')], default='pending', max_length=15)),
                ('game_type', models.CharField(choices=[('1v1', '1v1'), ('tournament', 'Tournament')], default='none', max_length=10)),
                ('game_id', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
            options={
                'unique_together': {('inviter', 'recipient', 'game_type', 'game_id')},
            },
        ),
    ]
